# this workflow runs when a release was published.
on:
  release:
    types: [published]

name: "release_published"
jobs:
  # Build the binary using GoReleaser
  build_binary:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4.2.2
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.6
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}
      -
        name: Load Build Variables
        uses: xom9ikk/dotenv@v2
      -
        name: Prepare .goreleaser.yml
        shell: bash
        run: envsubst < .goreleaser.yml > /tmp/.goreleaser.yml
      -
        name: GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          version: latest
          args: release --rm-dist --config /tmp/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
